Спринт #3. Инкремент #13
xbreathoflife/url-shortener pull request #14
Opened 2022-02-06 12:25 UTC by xbreathoflife

2022-02-07 13:48 UTC, lugingf requested changes
Основное - запрос внутри цикла и метод `Check`
Остальное по мелочи

2022-02-07 13:48 UTC, lugingf commented on internal/app/compress/gzip.go
> +		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
Так много пишем `"gzip"` что хочется в константу это вынести

2022-02-07 13:48 UTC, lugingf commented on internal/app/compress/gzip.go
> +		if r.Header.Get(`Content-Encoding`) == `gzip` {
а почему тут косые кавычки вдруг появились?

2022-02-07 13:48 UTC, lugingf commented on internal/app/storage/db.go
> +func (s *DBStorage) connect(_ context.Context) (*sql.DB, error) {
а чем у нас `connect` от `CheckConnect` отличаются? 

В `CheckConnect()` лучше использовать метод `sql.DB{}.Ping()`

2022-02-07 13:48 UTC, lugingf commented on internal/app/storage/db.go
> +	countURLQuery = "SELECT COUNT(*) as count FROM url"
Я второй раз уже вижу что народ выносит запросы в константы отдельно. У нас в материале так?
Просто обычно, если запрос не нужен более одного раза, то пишут прям внутри метода.
Но это не критично, если что

2022-02-07 13:48 UTC, lugingf commented on internal/app/storage/db.go
> +func (s *DBStorage) InsertNewURL(ctx context.Context, id int, baseURL string, shortenedURL string, uuid string) error {
Я почему обратил внимание на константы комментом выше - тут просто получается, что метод `Insert` настолько общий, что им можно вставлять вообще что угодно, если передать любой инсерт, а данные не по одному аргументу, а массивчиком  с многоточиями `...arguments`.

Но это тоже не критично, просто глаз зацепился

2022-02-07 13:48 UTC, lugingf commented on internal/app/storage/db.go
> +		if _, err = stmt.Exec(r.ID, r.BaseURL, r.ShortenedURL, r.UserID); err != nil {
Ой, ну не. Делать запросы в DB внутри цикла - это лишняя нагрузка. Надо либо все в один стейтмент собрать, либо в один инсерт

2022-02-08 20:43 UTC, xbreathoflife commented on internal/app/storage/db.go
> +	countURLQuery = "SELECT COUNT(*) as count FROM url"
Просто мне показалось, что будет удобнее вынести все запросы в один "блок"

2022-02-08 20:45 UTC, xbreathoflife commented
@lugingf поправила

2022-02-09 07:23 UTC, lugingf approved these changes

2022-02-09 07:26 UTC, merged