Спринт #1. Инкремент #3
xbreathoflife/url-shortener pull request #3
Opened 2022-01-08 15:12 UTC by xbreathoflife

2022-01-11 20:50 UTC, lugingf commented on internal/app/handler/handler.go
> +		urlID := store.GetNextID()
а зачем нам `nextID` ?

2022-01-11 20:51 UTC, lugingf commented on internal/app/handler/handler.go
> +		urlID := store.GetNextID()
А еще давай сделаем стуруктуру так, чтобы 
- хэндлер выполнял только работу с HTTP: прием запроса, валидация, отдавал ответ. И только вызывал сервис для выполнения бизнес-логики
- сервис работал с бизнес логикой и обращался бы в storage в случае необходимости

2022-01-11 20:53 UTC, lugingf requested changes
В общем хорошо, но оставил пару комментариев

2022-01-11 20:53 UTC, lugingf commented on internal/app/storage/storage.go
> +	storage.nextID++
все еще не понимаю зачем нам этот сдвиг

2022-01-12 14:56 UTC, xbreathoflife commented on internal/app/handler/handler.go
> +		urlID := store.GetNextID()
Избавилась от него и перешла на просто размер мапы, если речь была об этом)

2022-01-12 14:59 UTC, xbreathoflife commented
@lugingf Вроде бы все поправила)

2022-01-12 19:09 UTC, lugingf requested changes
Давай унесем проверки в тело хэндлера и уберем получение url по id

2022-01-12 19:09 UTC, lugingf commented on internal/app/server/server.go
> +	r.Get("/{urlID}", func(rw http.ResponseWriter, r *http.Request) {
Ммм, кажется чуть напутали тут. В роутере желательно чтобы было чисто - просто передали имя метода хэндлера и все. Все проверки валидности запроса и тд уже в теле метода хэндлера

2022-01-12 19:09 UTC, lugingf commented on internal/app/server/server.go
> +		us.handlers.GetURLHandler(rw, r, id)
Да, и вопрос, не заметил в прошлый раз - почему мы url по ID получаем?
По идее логика такая, что передав короткий url мы получаем развернутый. Как клиент узнает какой id ему надо передавать?

Видимо отсюда и появились `nextID()` :)

2022-01-12 20:33 UTC, xbreathoflife commented on internal/app/server/server.go
> +		us.handlers.GetURLHandler(rw, r, id)
В задании сказано что get мы делаем по идентификатору сокращённого URL -- у меня это как раз то самое id, потому что как мы иначе узнаем этот идентификатор, если он не в самом сокращенном URL? 
Сейчас получается мы делаем POST http://localhost:8080/ с каким-то [полным URL](https://yandex.ru/images/search?from=tabbar&text=cute%20cats&pos=1&img_url=https%3A%2F%2Fislam.ru%2Fsites%2Fdefault%2Ffiles%2Faddimg%2Fkittens_00.jpg&rpt=simage) и нам тогда вернется в ответе http://localhost:8080/0. И если мы сделаем GET http://localhost:8080/0 то перенесемся как раз на новую страницу.

Или можешь подробнее пояснить, где я что-то не так поняла? :)

2022-01-13 20:23 UTC, lugingf commented on internal/app/server/server.go
> +		us.handlers.GetURLHandler(rw, r, id)
Так, сори, виноват. Перепроверил задание, так и есть как ты говоришь) Тогда по этому комменту отбой. Извини, что запутал

2022-01-13 23:07 UTC, xbreathoflife commented on internal/app/server/server.go
> +		us.handlers.GetURLHandler(rw, r, id)
Фух, отлично) другой коммент исправила

2022-01-14 08:37 UTC, lugingf approved these changes
Хорошо)

2022-01-14 08:38 UTC, merged